version: '2'
services:
  proftp:
    image: proftp #quay.io/galaxy/proftpd:dev
    container_name: galaxy-proftp
    volumes:
        - ftp_config:/etc/proftpd/
        - ftp_data:/galaxy-central/database/ftp
    expose:
        - 21
    ports:
        - "8021:21"
    # proftpd config files from Galaxy are needed
    depends_on:
        - galaxy
    links:
        - galaxy:galaxy.local
    # restart: always
    hostname: galaxy-proftp


  galaxy:
    image: galaxy #quay.io/bgruening/galaxy
    environment:
      - NONUSE=proftp
      - GALAXY_CONFIG_BRAND=FOO
      - GALAXY_LOGGING=full
    ports:
      - "8080:80"
    #  - "8021:21"
      - "9002:9002"
    # proftpd needs postgres to check authentification
    expose:
     - 5432
    container_name: galaxy
    volumes:
     - ftp_config:/etc/proftpd/
     - ftp_data:/galaxy-central/database/ftp
     - ./galaxy-storage/:/export/
     - ./conf/postgresql.conf:/etc/postgresql/9.3/main/postgresql.conf
     - ./conf/pg_hba.conf:/etc/postgresql/9.3/main/pg_hba.conf
    #volumes:
    # - .:/code
    #logging:
    #    driver: syslog
    hostname: galaxy

volumes:
  ftp_config: {}
  ftp_data: {}
