version: '2'
services:
  proftpd:
    image: quay.io/galaxy/proftpd:dev
    container_name: galaxy-proftpd
    volumes:
     - ftp_config:/etc/proftpd/
     - ftp_data:/export/galaxy-central/database/ftp
    expose:
     - 21
    ports:
      - "8021:21"
    # config file from Galaxy needed
    depends_on:
     - galaxy
    # restart: always


  galaxy:
    image: galaxy #quay.io/bgruening/galaxy
    environment:
      - NONUSE=proftp
      - GALAXY_CONFIG_BRAND=FOO
      - GALAXY_LOGGING=full
    ports:
      - "8080:80"
    #  - "8021:21"
      - "9002:9002"
    # proftpd needs postgres to check authentification
    expose:
     - 5432
    container_name: galaxy
    volumes:
     - ftp_config:/etc/proftpd/
     - ftp_data:/export/galaxy-central/database/ftp
    #volumes:
    # - .:/code
    logging:
        driver: syslog

volumes:
  ftp_config: {}
  ftp_data: {}
